# Generated by Django 2.0.6 on 2018-07-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0016_auto_20170407_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tpl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='blog',
            field=models.ForeignKey(on_delete=None, to='repository.Blog', verbose_name='所属博客'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(null=True, on_delete=None, to='repository.Category', verbose_name='文章类型'),
        ),
        migrations.AlterField(
            model_name='article2tag',
            name='article',
            field=models.ForeignKey(on_delete=None, to='repository.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='article2tag',
            name='tag',
            field=models.ForeignKey(on_delete=None, to='repository.Tag', verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(on_delete=None, to='repository.Article', verbose_name='所属文章'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='user',
            field=models.OneToOneField(on_delete=None, to='repository.UserInfo'),
        ),
        migrations.AlterField(
            model_name='category',
            name='blog',
            field=models.ForeignKey(on_delete=None, to='repository.Blog', verbose_name='所属博客'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=None, to='repository.Article', verbose_name='评论文章'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='reply',
            field=models.ForeignKey(null=True, on_delete=None, related_name='back', to='repository.Comment', verbose_name='回复评论'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=None, to='repository.UserInfo', verbose_name='评论者'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='blog',
            field=models.ForeignKey(on_delete=None, to='repository.Blog', verbose_name='所属博客'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='processer',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='p', to='repository.UserInfo'),
        ),
        migrations.AlterField(
            model_name='trouble',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='u', to='repository.UserInfo'),
        ),
        migrations.AlterField(
            model_name='updown',
            name='article',
            field=models.ForeignKey(on_delete=None, to='repository.Article', verbose_name='文章'),
        ),
        migrations.AlterField(
            model_name='updown',
            name='user',
            field=models.ForeignKey(on_delete=None, to='repository.UserInfo', verbose_name='赞或踩用户'),
        ),
        migrations.AlterField(
            model_name='userfans',
            name='follower',
            field=models.ForeignKey(on_delete=None, related_name='followers', to='repository.UserInfo', verbose_name='粉丝'),
        ),
        migrations.AlterField(
            model_name='userfans',
            name='user',
            field=models.ForeignKey(on_delete=None, related_name='users', to='repository.UserInfo', verbose_name='博主'),
        ),
    ]
