# Generated by Django 2.0.6 on 2018-08-07 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0017_auto_20180729_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='个人博客标题'),
        ),
        migrations.AlterField(
            model_name='updown',
            name='user',
            field=models.ForeignKey(on_delete=None, to='repository.UserInfo', verbose_name='点赞用户'),
        ),
    ]
