# Generated by Django 2.0.6 on 2018-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0019_auto_20180807_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articledetail',
            name='article',
            field=models.OneToOneField(blank=True, null=True, on_delete=None, to='repository.Article', verbose_name='所属文章'),
        ),
    ]
